AllCops:
  Exclude:
    - 'bin/*'

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/FrozenStringLiteralComment:
  EnforcedStyle: always

Style/AccessorMethodName:
  Exclude:
    - 'lib/allscripts_api/client.rb'